### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: Unknown("error sending request for url (https://hexbear.net/api/v3/user/login)")

### ISSUE THREAD

**Issue by Cynosure-null** [LemmyNet/lemmy-client-rs#10]
I'm unsure if this is the right place for this, but upon running this:
```rust 
    let client = LemmyClient::new(ClientOptions {
    domain: String::from("hexbear.net"),
    secure: true
});
    let logininfo = Login{username_or_email: SensitiveString::from(env::var("bot_username").unwrap()),
password: SensitiveString::from(env::var("bot_password").unwrap()),
totp_2fa_token: None};

    client.login(logininfo).await.unwrap();
```

the thread panics on unwrapping `client.login(logininfo).await` with the message: `called `Result::unwrap()` on an `Err` value: Unknown("error sending request for url (https://hexbear.net/api/v3/user/login)")`

the error message from login is just `Unknown`

If I could get some guidance with this or if more verbose logging for errors could be added that would be ideal.

**Comment by airblast-dev** [comment]
It is likely this: https://github.com/LemmyNet/lemmy-client-rs/pull/9

Also the domain in the example uses 0.19.3. So you may have a few issues using the latest (0.19.4).

**Comment by SleeplessOne1917** [comment]
I published a [new lemmy-client version](https://crates.io/crates/lemmy-client/0.19.5-alpha.1) that has @airblast-dev's fix. If that still doesn't work for you, I reccomend using 0.19.3 for the time being until Hexbear upgrades.

**Comment by Cynosure-null** [comment]
Sorry for the late reply but that fixed it
