### ISSUE TITLE
Version Pinning for lemmy_api_common

### ISSUE THREAD

**Issue by airblast-dev** [LemmyNet/lemmy-client-rs#12]
Using an older version of the library loads the latest stable version of  `lemmy_api_common`. This makes using any older version of the library broken. This currently causes various structs to return errors related deserializing when using v0.19.3.

This normally is expected, however since lemmy's common library (and a few other libraries of lemmy as well) use unstable versioning, cargo adds the latest of the dependencies instead. Which in return means this libraries lemmy version mismatching with what the lemmy dependency is using.

Even in the case there isn't any compile error (which is what happened to me), it gives out confusing errors during runtime.

As a solution version pinning could be done.

```toml
[dependencies]
lemmy_api_common = {  version="=0.19.3"  }
```

This will tell cargo to load that exact version instead of the latest. This has the downside of `cargo update` not working with the dependency since it will simply use whatever the version we tell it to use. Once lemmy's libraries reach stable versioning this could be reverted to how it is currently.

To reproduce the issue simply create a new project and add this libraries any older version as the dependency (0.19.4 won't work since its the latest stable which leaves us with 0.19.3). After taking a look into `Cargo.lock` you will notice the dependencies that `lemmy-client` uses are the latest, which are very likely incompatible.

**Comment by SleeplessOne1917** [comment]
Added this in both the main branch and `v0.19.6` of this library.
