### ISSUE TITLE
Expose ClientOptions from LemmyClient

### ISSUE THREAD

**Issue by airblast-dev** [LemmyNet/lemmy-client-rs#13]
Currently there isn't a way to access the client options after initialization.

While the domain could be stored in a seperate variable, this adds an extra responsibility to keep things in sync with the client. Where as with the client options being exposed we can simply read the domain in a consistent manner (so we have the guarantee that the domain being read is the one that is in current use).

The use case I have for this is to be able to construct a URL from the domain. This would allow me to open the URL to a post or profile in a browser via other libraries. 

I think only allowing immutable access would be better to avoid confusing issues with the authentication stuff stored in the client.

If you would like this added I am happy to create a PR. 

Edit: Removed a bit of stuff as I forgot certain parts of the library were private.

**Comment by SleeplessOne1917** [comment]
Since the only other field in the `ClientOptions` is `secure`, which I don't think will need to be accessed, I could just make a method to get a read only reference to the domain. Will open a PR to show you what I mean.

**Comment by airblast-dev** [comment]
Thanks for the quick response, and your interest.

If the intention is to just display the domain, the `secure` field isn't needed as you said. However in order to construct the URL we would need to format it like done in https://github.com/LemmyNet/lemmy-client-rs/blob/9b7b4ae797748cfb06fe96b8923d3c91e77bbed4/src/lemmy_client_internal.rs#L20C1-L25C2. Meaning having access to the `secure` field could be useful when adding `http` or `https`. 

For a little more context, I want to be able to open a post by its ID in the browser using https://docs.rs/webbrowser/latest/webbrowser/fn.open.html. The reason for this is, I'm working an a TUI client for lemmy, and various parts (mainly images) don't really work too well in various terminal emulators. This would allow the user to simply open the URL in the browser in case they want to. I am aware it is a bit of niche use case but I don't really see any harm in allowing an immutable reference to the whole `ClientOptions` struct.

Still, just providing the domain name would simplify things quite a bit as most people would only care about the domain name.

**Comment by airblast-dev** [comment]
The method name could be a bit more clear, but other than that looks good.
